version: "3.9"
   
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrPass#456
  web:
    image: django-app-image
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=master
      - DB_SERVER=wl1-python-django_db_1
      - DB_PORT=1433
      - DB_USER=SA
      - DB_PASSWORD=StrPass#456
    depends_on:
      - db
