version: "3.9"
   
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrPass#456
  web:
    image: benchmark-dotnet
    ports:
      - "5187:80"
    environment:
      - DB_NAME=master
      - DB_SERVER=db
      - DB_USER=SA
      - DB_PASSWORD=StrPass#456
    depends_on:
      - db
