name: Python Django

on:
  push:
    branches: ['main']
    paths: ['apps/wl1-python-django/api/**']
    
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: apps/wl1-python-django/api/
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:apps/wl1-python-django/api/"
          push: true
          tags: epomatti/workload-benchmarks-python-django:latest
